import { BiLogoMicrosoft } from "react-icons/bi";
import { FaAws, FaC } from "react-icons/fa6";
import {
  RiCloudLine,
  RiDatabase2Line,
  RiFlowChart,
  RiFunctionLine,
  RiRobot2Line,
  RiServerLine,
} from "react-icons/ri";
import {
  SiApachekafka,
  SiBootstrap,
  SiCaddy,
  SiCplusplus,
  SiCss,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFigma,
  SiFlask,
  SiGin,
  SiGit,
  SiGo,
  SiGoland,
  SiGraphql,
  SiHtml5,
  SiInsomnia,
  SiIntellijidea,
  SiJavascript,
  SiJira,
  SiJquery,
  SiJupyter,
  SiKubernetes,
  SiLangchain,
  SiLanggraph,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiOpenai,
  SiOpenjdk,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPydantic,
  SiPycharm,
  SiPython,
  SiPytorch,
  SiRaspberrypi,
  SiReact,
  SiRedis,
  SiRedux,
  SiShadcnui,
  SiSocketdotio,
  SiSpring,
  SiSqlite,
  SiTailwindcss,
  SiTensorflow,
  SiThreedotjs,
  SiTypescript,
  SiUbuntu,
  SiVercel,
  SiVite,
  SiVuedotjs,
  SiWebpack,
  SiGithubactions,
} from "react-icons/si";
import { TbBrandAzure, TbBrandCSharp, TbBrandVscode } from "react-icons/tb";

// TechStack.jsx renders this file directly.
// To add a new skill, append it to the right category and optionally provide an icon.
const createSkill = (name, icon = null, abbr) => ({
  name,
  icon,
  abbr,
});

export const techStackGroups = [
  {
    title: "Programming Languages",
    description:
      "Core languages I use for product engineering, backend systems, automation, and performance-oriented work.",
    accentClassName: "text-amber-300",
    items: [
      createSkill("JavaScript", SiJavascript),
      createSkill("TypeScript", SiTypescript),
      createSkill("Python", SiPython),
      createSkill("Java", SiOpenjdk),
      createSkill("Go", SiGo),
      createSkill("C", FaC, "C"),
      createSkill("C++", SiCplusplus, "C++"),
      createSkill("C#", TbBrandCSharp, "C#"),
      createSkill("PHP", SiPhp),
      createSkill("Visual Basic", BiLogoMicrosoft, "VB"),
    ],
  },
  {
    title: "Frontend",
    description:
      "UI technologies, state tooling, and build systems I lean on to ship fast, responsive web experiences.",
    accentClassName: "text-cyan-300",
    items: [
      createSkill("HTML5", SiHtml5),
      createSkill("CSS3", SiCss),
      createSkill("jQuery", SiJquery),
      createSkill("React", SiReact),
      createSkill("React Native", SiReact, "RN"),
      createSkill("Vue.js", SiVuedotjs),
      createSkill("Next.js", SiNextdotjs),
      createSkill("Tailwind CSS", SiTailwindcss),
      createSkill("Shadcn/UI", SiShadcnui, "UI"),
      createSkill("Redux", SiRedux),
      createSkill("Zustand", RiFlowChart, "ZU"),
      createSkill("Vite", SiVite),
      createSkill("Webpack", SiWebpack),
      createSkill("Three.js", SiThreedotjs),
      createSkill("Bootstrap", SiBootstrap),
    ],
  },
  {
    title: "Backend",
    description:
      "Frameworks and service-layer tools I use to build APIs, orchestration pipelines, and scalable application backends.",
    accentClassName: "text-emerald-300",
    items: [
      createSkill("Node.js", SiNodedotjs),
      createSkill("Express.js", SiExpress),
      createSkill("FastAPI", SiFastapi),
      createSkill("Django", SiDjango),
      createSkill("Flask", SiFlask),
      createSkill("Spring", SiSpring),
      createSkill("Gin", SiGin),
      createSkill("GORM", RiDatabase2Line, "GO"),
      createSkill("GraphQL", SiGraphql),
      createSkill("Prisma", SiPrisma),
      createSkill("WebSocket", SiSocketdotio, "WS"),
      createSkill("Kafka", SiApachekafka),
    ],
  },
  {
    title: "Databases",
    description:
      "Relational and NoSQL storage systems I use for transactional workloads, analytics, caching, and high-volume querying.",
    accentClassName: "text-blue-300",
    items: [
      createSkill("MySQL", SiMysql),
      createSkill("PostgreSQL", SiPostgresql),
      createSkill("MongoDB", SiMongodb),
      createSkill("Redis", SiRedis),
      createSkill("SQLite", SiSqlite),
      createSkill("DynamoDB", RiDatabase2Line, "DDB"),
    ],
  },
  {
    title: "AI & ML",
    description:
      "Libraries and platforms I use for LLM workflows, evaluation, model integration, and machine learning experimentation.",
    accentClassName: "text-pink-300",
    items: [
      createSkill("LangChain", SiLangchain),
      createSkill("LangGraph", SiLanggraph),
      createSkill("LangSmith", RiRobot2Line, "LS"),
      createSkill("PydanticAI", SiPydantic, "PAI"),
      createSkill("OpenAI", SiOpenai),
      createSkill("PyTorch", SiPytorch),
      createSkill("TensorFlow", SiTensorflow),
    ],
  },
  {
    title: "Cloud & DevOps",
    description:
      "Infrastructure, deployment, and operations tools I use to containerize services, automate releases, and run workloads in production.",
    accentClassName: "text-orange-300",
    items: [
      createSkill("AWS", FaAws),
      createSkill("Azure", TbBrandAzure),
      createSkill("EC2", RiServerLine),
      createSkill("S3", RiCloudLine),
      createSkill("Lambda", RiFunctionLine),
      createSkill("RDS", RiDatabase2Line),
      createSkill("Docker", SiDocker),
      createSkill("Kubernetes", SiKubernetes),
      createSkill("Nginx", SiNginx),
      createSkill("Caddy", SiCaddy),
      createSkill("GitHub Actions", SiGithubactions, "GHA"),
      createSkill("CI/CD", RiFlowChart),
      createSkill("Vercel", SiVercel),
      createSkill("Netlify", SiNetlify),
    ],
  },
  {
    title: "Tools & Platforms",
    description:
      "The developer tooling and working environment I rely on for debugging, collaboration, experimentation, and delivery.",
    accentClassName: "text-violet-300",
    items: [
      createSkill("Git", SiGit),
      createSkill("Linux", SiLinux),
      createSkill("Ubuntu", SiUbuntu),
      createSkill("VS Code", TbBrandVscode, "VS"),
      createSkill("GoLand", SiGoland),
      createSkill("IntelliJ IDEA", SiIntellijidea, "IJ"),
      createSkill("PyCharm", SiPycharm),
      createSkill("Jupyter", SiJupyter),
      createSkill("Postman", SiPostman),
      createSkill("Insomnia", SiInsomnia),
      createSkill("Figma", SiFigma),
      createSkill("Jira", SiJira),
      createSkill("Raspberry Pi", SiRaspberrypi, "RP"),
    ],
  },
];
